repos:

  - repo: local
    hooks:
      - id: poetry-lint
        name: Poetry Lint 
        description: This hook runs `make lint` inside a relevant poetry environment.
        entry: poetry run make lint
        language: system
        types: [python]

      - id: poetry-test
        name: Poetry Test
        description: This hook runs `make test` inside a relevant poetry environment.
        entry: poetry run make test
        language: system
        types: [python]
