version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=clauselocator
      - POSTGRES_DB=clauselocator
      - POSTGRES_PASSWORD=clauselocator

  api:
    build: .
    volumes:
      - .:/app
      - storage:/storage
    depends_on:
      - db
    environment:
      - SECRET_KEY=CorrectHorseBatteryStaple
      - DATABASE_URL=postgres://clauselocator:clauselocator@db:5432/clauselocator

  caddy:
    build: caddy
    volumes:
      - storage:/storage
    ports:
      - 8000:80

volumes:
  storage:
