version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=clauselocator
      - POSTGRES_DB=clauselocator
      - POSTGRES_PASSWORD=clauselocator

  api:
    image: ghcr.io/jerbob/clauselocator
    volumes:
      - storage:/storage
    depends_on:
      - db
    environment:
      - SECRET_KEY=CorrectHorseBatteryStaple
      - DATABASE_URL=postgres://clauselocator:clauselocator@db:5432/clauselocator

  caddy:
    image: ghcr.io/jerbob/caddy
    volumes:
      - storage:/storage
    ports:
      - 8000:80

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30

volumes:
  storage:
