version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=clauselocator
      - POSTGRES_DB=clauselocator
      - POSTGRES_PASSWORD=clauselocator

  api:
    build:
      context: .
      args:
        - BUILD_ENV=dev
    command: python src/manage.py runserver 0.0.0.0:80
    volumes:
      - .:/app
      - storage:/storage
    depends_on:
      - db
    environment:
      - DEPLOY_ENV=dev
      - SECRET_KEY=CorrectHorseBatteryStaple
      - DJANGO_SETTINGS_MODULE=core.settings
      - DATABASE_URL=postgres://clauselocator:clauselocator@db:5432/clauselocator

  caddy:
    image: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - storage:/storage
    ports:
      - 8000:80

volumes:
  storage:
