name: Build containers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Container Registry
        run: echo ${{ secrets.GHTOKEN }} | docker login ghcr.io -u ${{ secrets.GHUSER }} --password-stdin

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build project containers
        run: make build

      - name: Deploy to Github Container Registry
        run: make deploy-live
