name: Build containers

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Github Container Registry
        run: echo ${{ secrets.GHTOKEN }} | docker login ghcr.io -u ${{ secrets.GHUSER }} --password-stdin

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build project containers
        run: make build

      - name: Deploy to Github Container Registry
        run: make deploy-live

      - name: Install poetry and project dependencies
        uses: knowsuchagency/poetry-install@v1
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Generate coverage report
        run: poetry run make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./src/coverage.xml
          directory: ./coverage/reports/
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
